steps:
  # Install Node.js and npm dependencies
  - name: 'node:18'  
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install

  # Deploy to GCP VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp --recurse . reset@node-dev-server:/home/reset/nodedevserver1 --zone=us-central1-b

options:
  logging: CLOUD_LOGGING_ONLY
