steps:
  # Install Node.js and npm dependencies
  - name: 'node:18'  
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install

  # Deploy to VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp --recurse ./ reset@node-dev-server:/home/reset/nodedevserver --zone=us-central1-b