steps:
  # Install Node.js and npm dependencies
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install

  # Compress files into a tar archive for transfer, excluding the tar file itself
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        tar --exclude='./project.tar.gz' -czf /workspace/project.tar.gz -C $(pwd) .

  # Copy the tar archive to the GCP VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp /workspace/project.tar.gz reset@node-dev-server:/home/reset/project.tar.gz --zone=us-central1-b

  # Extract the tar archive on the GCP VM instance and overwrite files
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh reset@node-dev-server --zone=us-central1-b --command="tar -xzf /home/reset/project.tar.gz -C /home/reset/nodedevserver && rm /home/reset/project.tar.gz"

options:
  logging: CLOUD_LOGGING_ONLY
